bookmarks/urls.py
from django.conf.urls import patterns, url
from bookmarks import views


urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^add_list/$', views.add_list, name='add_list'),
	url(r'^list/(?P<list_name_url>\w+)/$', views.list, name='lists'),
	url(r'^list/(?P<list_name_url>\w+)/add_link/$', views.add_link, name='add_link'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^delete_link/(?P<link_id>\w+)/$', views.delete_link, name='delete_link'),
	url(r'^restricted/', views.restricted, name='restricted'),
	url(r'^logout/$', views.user_logout, name='logout'),
	)

v2/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bookmarks/', include('bookmarks.urls')),
    url(r'^', include('bookmarks.urls'))

)

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User

class List(models.Model):
    name = models.CharField(max_length = 50)
    date_created = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)

class Link(models.Model):
	lists = models.ForeignKey(List)
	name = models.CharField(max_length = 50)
	link = models.URLField()
	date_created = models.DateTimeField(auto_now_add = True)
	date_modified = models.DateTimeField(auto_now = True)
	tags = models.TextField(null = True, blank = True)

class User(models.Model):
	user = models.OneToOneField(User)
	internal_id = models.CharField(max_length = 25, null = True, blank= True)
	verified = models.BooleanField(default = False)
	approval_date = models.DateTimeField(null = True, blank = True)



	

bookmarks/forms.py
from django import forms
from bookmarks.models import Link, List
from django.contrib.auth.models import User

class ListForm(forms.ModelForm):
	name = forms.CharField(max_length = 50, help_text="Enter the name of the list:")

	class Meta:
			model = List

class LinkForm(forms.ModelForm):
	name = forms.CharField(max_length = 50, help_text="Name")
	link = forms.URLField(max_length=200, help_text="URL")
	tags = forms.CharField(help_text = "Tags")

	class Meta:
		model = Link
		fields = ('name', 'link', 'tags')

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'password' )

class DeleteForm(forms.ModelForm):
	class Meta:
		model = Link
		fields = []

bookmarks/views.py
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from bookmarks.models import List, Link, User
from bookmarks.forms import ListForm, LinkForm, UserForm, DeleteForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


def encode_url(str):
    return str.replace(' ', '_')

def decode_url(str):
    return str.replace('_', ' ')

@login_required
def restricted(request):
    return HttpResponse("You can see this file if logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/bookmarks/')


def index(request): 
    context = RequestContext(request)
    list_order = List.objects.order_by('name')
    context_dict = {'lists': list_order}
    links = Link.objects.order_by('lists')

    for lists in list_order:
        lists.url = lists.name

    context_dict['links'] = links

    return render_to_response('bookmarks/index.html', context_dict, context)

def list(request, list_name_url):
	context = RequestContext(request)
	list_name = list_name_url 
	context_dict = {'list_name': list_name, 'list_name_url':list_name_url}

	try:
		lists = List.objects.get(name=list_name)
		links = Link.objects.filter(lists=lists)
		context_dict['lists'] = lists
		context_dict['links'] = links
	except List.DoesNotExist:
		pass

	return render_to_response('bookmarks/list.html', context_dict, context)

@login_required
def add_list(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = ListForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print form.errors
    else:
        form = ListForm()
    return render_to_response('bookmarks/add_list.html', {'form': form}, context)


@login_required
def add_link(request, list_name_url):
    context = RequestContext(request)
    list_name = decode_url(list_name_url)
    if request.method == 'POST':
        form = LinkForm(request.POST)

        if form.is_valid():
            link = form.save(commit=False)

            try:
                lis = List.objects.get(name=list_name)
                link.lists = lis
            except List.DoesNotExist:
                return render_to_response('bookmarks/add_link.html', {}, context)

            link.save()
            return HttpResponseRedirect('/bookmarks/')
        else:
            print form.errors
    else:
        form = LinkForm()
    return render_to_response( 'bookmarks/add_link.html',
            {'list_name_url': list_name_url,
             'list_name': list_name, 'form': form},
             context)

def register(request):
    context = RequestContext(request)
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            registered = True

        else:
            print user_form.errors
    else:
        user_form = UserForm()

    return render_to_response(
        'bookmarks/register.html',
        {'user_form': user_form, 'registered': registered},
        context)

def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/bookmarks/')
            else:
                return HttpResponse("Your account is inactive.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    else:
        return render_to_response('bookmarks/login.html', {}, context)

@login_required
def delete_link(request, link_id):
    link_to_delete = get_object_or_404(Link, id=link_id)
    context = RequestContext(request)
    link_to_delete.delete()
    return HttpResponseRedirect('/bookmarks/')

templates/bookmarks/add_link.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <div class="container">
        <form class ="form-horizontal" id="link_form" method="post" action="/bookmarks/list/{{ list_name_url }}/add_link/"> <legend style="font-size:35px;font-family:arial;"> Add a Link </legend>

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}

            <div class="control-group">
                <label class="control-label" for="id_name"> Name</label>
                <div class="controls">
                    <input class ="form-control" type="text" placeholder = "Enter name" name="name"  id="id_name"/> 
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_link"> URL</label>
                <div class="controls">
                    <input class ="form-control" type="url" placeholder = "URL" name="link"   id="id_link"/> 
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_tags"> Tags</label>
                <div class="controls">
                    <textarea class = "form-control" rows= "3" id="id_tags" name="tags" > </textarea> 
                </div>
            </div>


            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Create Link</button>
        </form>
    </div>
</div>

{% endblock %}

templates/bookmarks/add_list.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <div class="container">
        <form class ="form-horizontal" id="list_form" method="post" action="/bookmarks/add_list/"><legend style="font-size:35px;font-family:arial;"> Add a List </legend>

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}

            <div class="control-group">
                <label class="control-label" for="id_name"> Name</label>
                <div class="controls">
                    <input class ="form-control" type="text" placeholder = "Enter name" name="name"  id="id_name"/> 
                </div>
            </div>

            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Create List</button>
        </form>
    </div>
</div>


{% endblock %}

templates/bookmarks/base.html
<!DOCTYPE html>

<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> 


<html>
<head>
    <title>{% block title %}Bookmarks{% endblock %}</title>
</head>

<body>
    <div>
        {% block body_block %}{% endblock %}
    </div>

    <hr />

    <div>
        <ul>
            {% if user.is_authenticated %}
            <a href="/bookmarks/logout/">Logout</a></br>
            <a href="/bookmarks/add_list/">Create a New List</a></br>
            {% else %}
            <a href="/bookmarks/register/">Register</a></br>
            <a href="/bookmarks/login/">Login</a></br>
            {% endif %}

            <a href="/bookmarks/">Go to Lists</a>
        </ul>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/bookmarks/delete_link.html
{% if object %}
    <a href="{{ object.get_admin_delete_url }}">Delete</a> |

{% endif %}

templates/bookmarks/index.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}



{% if lists %}
<div class="panel-group" id="accordion"  style="margin-right:100px;">  <legend style="font-size:35px;font-family:arial;margin-left:40px;"> Lists </legend>
    {% for list in lists %}
    <div class="panel panel-default"  style="margin-left:40px;">
        <div class="panel-heading" style="background-color:white;" >
            <h4 class="panel-title" style="background-color:white;font-size:regular;font-family:arial;" >
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ list.name}}">
                    {{ list.name }}
                </a>
            </h4>
        </div>
        <div id="collapse{{ list.name }}" class="panel-collapse collapse">
            <div class="panel-body">
                {% if links %}
                <table class = "table table-condensed">
                    <tr>
                        <th>Link</th>
                    </tr>
                    {% for link in links %}
                    {% if link.lists_id == list.id %}
                    <tr>
                       <td><a href="{{ link.link }}">{{ link.name }}</a></td>
                       {% if user.is_authenticated %}
                       <td><a href='/bookmarks/delete_link/{{ link.pk }}/'> Delete</a></td>
                       {% endif %}
                    {% endif %}
                   </tr>

                   {% endfor %}
                   <tr>
                    <td><a href="/bookmarks/list/{{ list.name }}/add_link/">Add a New Link</a></td>
                </tr>
            </table>
            {% else %}
            <strong>No links currently in list.</strong>
            {% endif %}
        </div>
    </div>
</div>





{% endfor %}

{% else %}
<strong>There are no lists present.</strong>
{% endif %}

{% endblock %}

templates/bookmarks/list.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}
        <h1>{{ list_name }}</h1>
        {% if lists %}
            {% if links %}
            <table style="width:300px">
                <style>
                 tr, table
                {
                    border:1px solid black;
                }
                </style>
              
                <tr>
                    <th>Name</th>
                    <th>Tags</th>
                    <th>Date Created</th>
                </tr>
                {% for link in links %}
                <tr>
                    <td style="border:1px solid black"><a href="{{ link.link }}">{{ link.name }}</a></td>
                    <td style="border:1px solid black">{{ link.tags }}</td>
                    <td style="border:1px solid black">{{ link.date_created }}</td>
                    {% if user.is_authenticated %}
                    <td><a href='/bookmarks/delete_link/{{ link.pk }}/'> Delete</a></td>
                    {% endif %}
                </tr>

                {% endfor %}
            </table>
 
            {% else %}
                <strong>No links currently in list.</strong>
            {% endif %}
        {% else %}
            The specified list {{ list_name }} does not exist!
        {% endif %}
        <br>
        <a href="/bookmarks/list/{{ list_name_url }}/add_link/">Add a New Link</a>
        </br>
{% endblock %}

templates/bookmarks/login.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}

<style>
body {
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #ddd;
}

.container-login {
  width:300px;
  height:350px;
  margin:0 auto;
  position:relative;
  
}

.checkbox {
  font-weight: normal;

}
</style>


<div class="container-login">
  <form class="form-signin" id="login_form" method="post" action="/bookmarks/login/">
    <h2 class="form-signin-heading">Please sign in</h2>
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Email address" name="username" value="" size="50"  />
    <input type="password" class="form-control" placeholder="Password" name="password" value="" size="50"  />
    <label class="checkbox">
      <input type="checkbox"> Remember Me
    </label>
    <button class="btn btn-block btn-primary" type="submit" >Sign in</button>
  </form>
</div>



           <!-- <input type="submit" value="submit" />
            {% if registered == False %}
            <a href="/bookmarks/register/">Register</a>
            {% endif %}
            <a href='/bookmarks/'>Back</a>
        </form>

        //-->
        {% endblock %}

templates/bookmarks/register.html
{% extends 'bookmarks/base.html' %}

{% block title %}{{ list_name }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <legend style="font-size:35px;font-family:arial;margin-left:50px;"> Create User </legend>
    {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="/bookmarks/">Return to the homepage.</a><br />
    {% else %}


    <div class="container">

        <form class="form-signin" id="user_form" method="post" action="/bookmarks/register/"
        enctype="multipart/form-data">

        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <button class="btn btn-large btn-primary" type="submit" >Register</button>
    </form>
</div>
</div>
{% endif %}

{% endblock %}